[2024-04-26T22:34:39.235+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T22:34:39.283+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Crypto_ETL.predict_price scheduled__2024-04-23T00:00:00+00:00 [queued]>
[2024-04-26T22:34:39.305+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Crypto_ETL.predict_price scheduled__2024-04-23T00:00:00+00:00 [queued]>
[2024-04-26T22:34:39.307+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-26T22:34:39.344+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): predict_price> on 2024-04-23 00:00:00+00:00
[2024-04-26T22:34:39.368+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=338) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-26T22:34:39.372+0000] {standard_task_runner.py:63} INFO - Started process 353 to run task
[2024-04-26T22:34:39.372+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Crypto_ETL', 'predict_price', 'scheduled__2024-04-23T00:00:00+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/processing_ETL.py', '--cfg-path', '/tmp/tmpqizqv6ra']
[2024-04-26T22:34:39.374+0000] {standard_task_runner.py:91} INFO - Job 116: Subtask predict_price
[2024-04-26T22:34:39.503+0000] {task_command.py:426} INFO - Running <TaskInstance: Crypto_ETL.predict_price scheduled__2024-04-23T00:00:00+00:00 [running]> on host 7542c54372fc
[2024-04-26T22:34:39.690+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Crypto_ETL' AIRFLOW_CTX_TASK_ID='predict_price' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-23T00:00:00+00:00'
[2024-04-26T22:34:39.693+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T22:34:39.701+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T22:34:39.702+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/processing_ETL.py", line 103, in _Predict_Price
    df_final=pd.read_csv('/opt/airflow/dags/final_dataset.csv', parse_dates='Date')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1723, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 61, in __init__
    super().__init__(kwds)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/base_parser.py", line 125, in __init__
    self.parse_dates = _validate_parse_dates_arg(kwds.pop("parse_dates", False))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/base_parser.py", line 1420, in _validate_parse_dates_arg
    raise TypeError(msg)
TypeError: Only booleans, lists, and dictionaries are accepted for the 'parse_dates' parameter
[2024-04-26T22:34:39.721+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=Crypto_ETL, task_id=predict_price, execution_date=20240423T000000, start_date=20240426T223439, end_date=20240426T223439
[2024-04-26T22:34:39.743+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 116 for task predict_price (Only booleans, lists, and dictionaries are accepted for the 'parse_dates' parameter; 353)
[2024-04-26T22:34:39.789+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-26T22:34:39.828+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T22:34:39.838+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
